### ISSUE TITLE
Keine Animation

### ISSUE THREAD

**Issue by dp-designpilot** [plenta/contao-countup-bundle#2]
Hallo

Ich habe die Erweiterung über den **Contao Manager** installiert und wollte jetzt ein **Elementtyp** -> **Count up** definieren mit folgenden Angaben:

[![Bildschirmfoto-2022-01-16-um-10-06-59.png](https://i.postimg.cc/Jh7wZ1V8/Bildschirmfoto-2022-01-16-um-10-06-59.png)](https://postimg.cc/0z4Hq1yX)

An was kann das liegen? Ich habe die Contao 4.12.5 installiert falls das eine rolle spielt

**Comment by chwchw** [comment]
Hallo, bei uns funktioniert es.
Hier ist der Link:
https://plenta.io/contao-erweiterungen/d/contao-count-up-bundle

Welchen Browser verwendest du?
Zeigt die Browser-Console einen Fehler?
Hast du eine Beispielseite auf der es nicht funktioniert?

**Comment by dp-designpilot** [comment]
Hallo chwchw

Ich kann Dir die Seite Online stellen sobald ich zu Hause bin (wie lange wärst Du denn noch Online oder hast Du Slack??)

**Comment by dp-designpilot** [comment]
Wie sieht es jetzt aus ????

**Comment by dp-designpilot** [comment]
Hallo Christoph
Die Erweiterung müsste ja in der Contao 4.12.5 Out of de Box funktioniere oder ???? Einfach ein Inhaltselement vom Typ Count Up definieren und die Einstellungen machen.

**Comment by chwchw** [comment]
CSS Fehler: Die Höhe der <span>-Element (.countUpPrefix, .countUpValue, .countUpSuffix) in .ce_plenta_countup dürfen nicht höher sein als die Höhe des .ce_plenta_countup-Elements.

**Comment by dp-designpilot** [comment]
Hallo Christoph
Dann muss ich in meinem CSS File blos bei .countUpSufix , .countUpPraefix und .countUpValue ein display: inline-block; machen sehe ich das richtig ??

**Comment by chwchw** [comment]
Nein. Wenn das Problem von Contao-Reset kommt und du das grundlegende CSS noch nicht fertig hast, dann bitte keine dedizierten CSS-Angaben für einzelne Elemente schreiben.

**Comment by dp-designpilot** [comment]
Ok dann weiss ich Bescheid, allenfalls komm ich dann nochmal darauf zurück (auf jeden Fall weiss ich jetzt wo der Fehler ist)
