### ISSUE TITLE
Zahlengruppierung funktioniert nicht

### ISSUE THREAD

**Issue by dive13** [plenta/contao-countup-bundle#4]
Contao: 4.13.15
php: 8.1.15
Bundle: 2.1.1

Hi, danke für die praktische Erweiterung. Es klappt alles bis auf die Gruppierung. Egal, ob im BE die checkbox "Zahlengruppierung" aktiviert ist oder nicht – im FE bleibt data-usegrouping immer "false", es wird also kein Tausender-Trennzeichen ausgegeben.

**Comment by chwchw** [comment]
@dive13 Fixed in 2.1.2

**Comment by dive13** [comment]
Perfekt, danke!
